---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Careers
- type: heading
  label: Pages
- type: directory
  path: pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Posts
- type: heading
  label: Landing Pages
- type: heading
  label: Site-wide
- type: heading
  label: Templates
upload_dir: ''
public_path: https://valufirstvc-images.s3.ap-southeast-2.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
